<?php

namespace AppBundle\Repository;

use AppBundle\Repository\FlightRepository;
use AppBundle\Entity\Flight;
use AppBundle\Entity\Customer;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{

}
