<?php

namespace AppBundle\Repository;

use AppBundle\Repository\FlightRepository;
use AppBundle\Entity\Flight;
use AppBundle\Entity\Customer;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function bookAFlight($flightId, $customerId ){

      $em = $this->getEntityManager();
      $qb = $em->createQueryBuilder();

      $results = $qb->select('f')
                	->from('AppBundle:Flight', 'f')
                	->where('f.id  = :flightId')
                  ->setParameter('flightId' , $flightId)
                	->getQuery()
                	->getResult();

      try {

        	return $results;
    	} catch (\Doctrine\ORM\NoResultException $e) {
        	return null;
    	}

    }


}
