<?php

namespace AppBundle\Repository;

/**
 * FlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightRepository extends \Doctrine\ORM\EntityRepository
{

  public function getAvailableFlights($departing, $flyingFrom, $flyingTo, $nbrPassengers){

    $em = $this->getEntityManager();

    $query = $em->createQueryBuilder()
                ->select('f')
                ->from('AppBundle:Flight', 'f')
                ->where('f.departingDate = :departing AND
                f.flyingFrom = :flyingFrom AND
                f.flyingTo = :flyingTo AND
                f.seatsLeft >= :nbrPassengers')
                ->setParameters( array('departing' => $departing ,
                                      'flyingFrom' => $flyingFrom ,
                                      'flyingTo' => $flyingTo,
                                      'nbrPassengers' => $nbrPassengers))
                ->getQuery();

    return $query->getResult();
  }

  public function getQueryAllFlights(){
    $em = $this->getEntityManager();

    return $em->createQueryBuilder()
                      ->select('f')
                      ->from('AppBundle:Flight', 'f')
                      ->getQuery();
  }


  public function getAllBookingsPerCustomer($customerId){
    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

    $results = $qb->select(array('b', 'f'))
                ->from('AppBundle:Booking', 'b')
                ->join('b.flight', 'f')
                ->where('b.customer = :customerId')
                ->setParameter('customerId' , $customerId)
                ->getQuery()
                ->getResult();

    try {

        return $results;
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }

  }

}
