# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER]
        ROLE_USER: [ROLE_CUSTOMER]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        AppBundle\Entity\Customer:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [ in_memory, db_provider ]

        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$vJMAeymNzyzQ0GLoWFZ82.PwoYHvtsp7YdtbejEZYa3PtmpF37laO
                        roles: 'ROLE_ADMIN'

        db_provider:
            entity:
                class: AppBundle:Customer
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
            logout: true
            anonymous: ~
        secured_area:
            form_login:
                csrf_token_generator: security.csrf.token_manager
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
