AppBundle\Entity\Booking:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BookingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bookingDate:
            type: datetime
            nullable: true
            column: booking_date
        reservedSeats:
            type: integer
            column: seats_left
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        customer:
            targetEntity: Customer
            inversedBy: bookings
            joinColumn:
                name: customer_id
                referencedColumnName: id
        flight:
            targetEntity: Flight
            inversedBy: bookings
            joinColumn:
                name: flight_id
                referencedColumnName: id
