AppBundle\Entity\Customer:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CustomerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: '64'
    lifecycleCallbacks: {  }
    oneToMany:
        bookings:
            targetEntity: Booking
            mappedBy: Customer
